# Generated by Django 3.2.12 on 2023-06-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('area', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('matricula', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('cargo', models.CharField(max_length=50)),
                ('data_admissao', models.DateField(auto_now_add=True)),
                ('data_demissao', models.CharField(blank=True, max_length=12, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incio', models.CharField(max_length=20)),
                ('data_final', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=2)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias', to='api.funcionario')),
            ],
        ),
    ]
