# Generated by Django 3.2.12 on 2023-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
